name: tekartik_audio_web_app
description: Audio test
version: 0.2.0
#homepage: https://www.example.com
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  tekartik_test_menu_browser:
    git:
      url: https://github.com/tekartik/test_menu.dart
      path: test_menu_browser
    version: '>=0.4.7'
  tekartik_audio_web:
    git:
      url: https://github.com/tekartikprj/audio_web
      path: audio_web'

dev_dependencies:
  process_run: ">=1.2.4"
  test: ">=1.26.3"
  build_runner: ">=2.10.0"
  build_web_compilers: ">=4.3.0"
resolution: workspace
