name: tekartik_audio_web
description: Audio for the web
version: 0.2.1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  path: ">=1.9.1"
  web:
  http:
  tekartik_browser_utils:
    git:
      url: https://github.com/tekartik/browser_utils.dart
    version: '>=0.1.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart

dev_dependencies:
  test: ">=1.26.3"
  process_run: ">=1.2.4"
resolution: workspace
